version: '3.8'
services:
  api:
    #image: egor-korobeinikov/app-news_blog-dockerized
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:11111111@postgres:5432/news_blog
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3001:3000'

  postgres:
    image: postgres:15.2
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111111
      POSTGRES_DB: news_blog
